packages:
  - apps/*
  - packages/*
  - server/*

catalogs:
  utils:
    axios: ^1.8.4
    lodash-es: 4.17.21
    qs: 6.14.0
    classnames: ^2.1.6
    "@types/qs": 6.14.0
    "@types/lodash-es": 4.17.12

  git:
    commitizen: ^4.3.0
    cz-git: ^1.7.0
    lefthook: ^2.0.4
    "@commitlint/cli": ^17.6.7
    "@commitlint/config-conventional": ^17.6.7

  lint:
    "@biomejs/biome": 1.9.4
    lint-staged: ~15.4.0

  node:
    typescript: ~5.7.3
    "@types/node": 18.11.9

  tailwindcss:
    "@tailwindcss/postcss": ^4.1.16
    tailwindcss: ^3.4.18
    postcss: ^8.5.3
    postcss-loader: ^8.1.1
    tw-animate-css: ^1.2.5
    tailwind-merge: ^3.2.0
    clsx: ^2.1.1
